# Generated by Django 4.0.6 on 2022-07-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermodel',
            name='course',
            field=models.CharField(default='c++', max_length=50),
        ),
        migrations.AddField(
            model_name='registermodel',
            name='dob',
            field=models.DateField(default='2002-05-26'),
        ),
        migrations.AddField(
            model_name='registermodel',
            name='gender',
            field=models.CharField(default='m', max_length=50),
        ),
        migrations.AddField(
            model_name='registermodel',
            name='phone',
            field=models.CharField(default='9755478801', max_length=12),
        ),
        migrations.AddField(
            model_name='registermodel',
            name='profession',
            field=models.CharField(default='Job', max_length=50),
        ),
    ]
